# Generated by Django 5.2.4 on 2025-07-17 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_user_username_alter_user_email_userextraprofile'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextraprofile',
            name='following_departments',
            field=models.ManyToManyField(blank=True, related_name='department_followers', to='home.subdepartmentpage'),
        ),
        migrations.AddField(
            model_name='userextraprofile',
            name='following_users',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to='custom_user.userextraprofile'),
        ),
        migrations.AddField(
            model_name='userextraprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='custom_user.userextraprofile'),
        ),
        migrations.AddField(
            model_name='userextraprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
