# Generated by Django 5.2.4 on 2025-07-17 07:39

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailusers', '0014_userprofile_contrast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_client_id', models.CharField(blank=True, default='', help_text='Google OAuth Client ID', max_length=255)),
                ('google_secret_key', models.CharField(blank=True, default='', help_text='Google OAuth Secret Key', max_length=255)),
                ('microsoft_client_id', models.CharField(blank=True, default='', help_text='Microsoft Azure Client ID', max_length=255)),
                ('microsoft_secret_key', models.CharField(blank=True, default='', help_text='Microsoft Azure Secret Key', max_length=255)),
                ('workday_client_id', models.CharField(blank=True, default='', help_text='Workday API Client ID', max_length=255)),
                ('workday_secret_key', models.CharField(blank=True, default='', help_text='Workday API Secret Key', max_length=255)),
            ],
            options={
                'verbose_name': 'Authentication Settings',
            },
        ),
        migrations.CreateModel(
            name='BlogPostDisplaySnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_blogpost', models.BooleanField(default=False, help_text='Check this box to enable the blogpost listing feature.')),
            ],
            options={
                'verbose_name': 'Blog Post Display',
                'verbose_name_plural': 'Custom_Blog_Post_Display',
            },
        ),
        migrations.CreateModel(
            name='BlogPostSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_post', models.BooleanField(default=False, help_text='Check this box to enable the blogpost feature.')),
            ],
            options={
                'verbose_name': 'Blog Post Setting',
                'verbose_name_plural': 'Custom_Blog_Post_Settings',
            },
        ),
        migrations.CreateModel(
            name='CalendarSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_calendar', models.BooleanField(default=False, help_text='Check this box to enable the calendar feature.')),
            ],
            options={
                'verbose_name': 'Calendar Setting',
                'verbose_name_plural': 'Custom_Calendar_Settings',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousels',
            },
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for this slide', max_length=200)),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
            },
        ),
        migrations.CreateModel(
            name='CarouselsSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the collection of carousels', max_length=100)),
            ],
            options={
                'verbose_name': 'Carousel Collection',
                'verbose_name_plural': 'Custom_Carousal',
            },
        ),
        migrations.CreateModel(
            name='CustomLoginSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome', help_text='Login page title', max_length=255)),
                ('background_color', models.CharField(default='#ff5733', help_text='Background color in hex format (e.g. #ffffff)', max_length=50)),
                ('text_color', models.CharField(default='#ffffff', help_text='Background color in hex format (e.g. #ffffff)', max_length=50)),
            ],
            options={
                'verbose_name': 'Custom Login Settings',
            },
        ),
        migrations.CreateModel(
            name='EventSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('work_anniversary', 'Work Anniversary'), ('wedding', 'Wedding')], default='birthday', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Custom_Events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FetchCalendarEventsSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_public_url', models.URLField(help_text='Enter the URL from which calendar events will be fetched.', max_length=500)),
            ],
            options={
                'verbose_name': 'Fetch Calendar Events Snippet',
                'verbose_name_plural': 'Fetch Calendar Events Snippets',
            },
        ),
        migrations.CreateModel(
            name='FetchURLSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_data_url', models.URLField(help_text='Enter the URL from which data will be fetched.', max_length=500)),
            ],
            options={
                'verbose_name': 'Fetch URL Snippet',
                'verbose_name_plural': 'Custom Fetch URL Snippets',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image_title', models.CharField(max_length=100)),
                ('is_full', models.BooleanField(default=False, verbose_name='Full Width (100%)')),
                ('is_half', models.BooleanField(default=False, verbose_name='Half Width (50%)')),
                ('is_fourth', models.BooleanField(default=False, verbose_name='One-Fourth (25%)')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleDriveSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_gdrive', models.BooleanField(default=False, help_text='Check this box to enable the Google Drive functionality.')),
                ('fetch_by_default', models.BooleanField(default=True, help_text='If enabled, drive data will be fetched automatically. If disabled, a fetch button will be shown.')),
            ],
            options={
                'verbose_name': 'Google Drive Setting',
                'verbose_name_plural': 'Custom_Google_Drive_Settings',
            },
        ),
        migrations.CreateModel(
            name='ImageGallerySnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Image Gallery',
                'verbose_name_plural': 'Custom_Slides_For_Crousals',
            },
        ),
        migrations.CreateModel(
            name='OneDriveSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_onedrive', models.BooleanField(default=False, help_text='Check this box to enable the OneDrive functionality.')),
                ('fetch_by_default', models.BooleanField(default=True, help_text='If enabled, drive data will be fetched automatically. If disabled, a fetch button will be shown.')),
            ],
            options={
                'verbose_name': 'OneDrive Setting',
                'verbose_name_plural': 'Custom_OneDrive_Settings',
            },
        ),
        migrations.CreateModel(
            name='OutlookCalendarSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_outlook_calendar', models.BooleanField(default=False, help_text='Check this box to enable the Outlook Calendar functionality.')),
            ],
            options={
                'verbose_name': 'Outlook Calendar Setting',
                'verbose_name_plural': 'Custom_Outlook_Calendar_Settings',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('votes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuillImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quill_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDaySnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_workday', models.BooleanField(default=False, help_text='Check this box to enable the workday checkin/checkout feature.')),
            ],
            options={
                'verbose_name': 'Workday Snippet',
                'verbose_name_plural': 'Custom Workday Snippets',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceCardSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, choices=[('document', 'Document'), ('folder', 'Folder'), ('user', 'User'), ('settings', 'Settings'), ('plus', 'Plus')], help_text='Select an SVG icon', max_length=50)),
                ('title', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Workspace Card',
                'verbose_name_plural': 'Custom_Workspace_Cards',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('question', 'Question'), ('poll', 'Poll')], default='post', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Required for questions', max_length=200, null=True)),
                ('body', wagtail.fields.RichTextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('likes_count', models.IntegerField(default=0, null=True)),
                ('poll_end_time', models.DateTimeField(blank=True, help_text='Set when this poll should end', null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailusers.userprofile')),
                ('likes', models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
    ]
