# Generated by Django 5.2.4 on 2025-07-17 07:39

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        ('custom_media', '0001_initial'),
        ('home', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subdepartment',
            field=models.ForeignKey(blank=True, help_text='Select a subdepartment for this blog post or leave blank for a global post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='home.subdepartmentpage'),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='carousel',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='components.carousel'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='parent',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousels', to='components.carouselssnippet'),
        ),
        migrations.AddField(
            model_name='customloginsettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='custom_media.customimage'),
        ),
        migrations.AddField(
            model_name='eventsnippet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='custom_media.customimage'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='gallery',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='components.imagegallerysnippet'),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='image_gallery',
            field=models.ForeignKey(help_text='Select an image gallery for this slide', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_slides', to='components.imagegallerysnippet'),
        ),
        migrations.AddField(
            model_name='polloption',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='components.blogpost'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.polloption'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.blogpost'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacecardsnippet',
            name='button_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('user', 'post')},
        ),
    ]
